name: CI/CD Pipeline

on: 
  push: 
    branches:
      - main
  pull_request:
    branches:
      -main

jobs:
   test:
    run-on: ubuntu-latest

    steps:
     - name: checkout code
       uses: actions/checkout@v2

     - name: Set up Docker Buildx
       uses: docker/setup-qemu-actions@v2

     - name: Ensure Docker Compose is available
       uses: docker-compose version

     - name: Copy .env.example to .env
       uses: cp ./4-integration-test/.env.example ./1-integration-test/.env
       
     - name: Run integration script
       run:  cd 1-integration-test && npm run test:integration